theme: jekyll-theme-minimal
title: Florin Lipan
description: My personal website
url: https://lipanski.com
permalink: posts/:slug
twitter:
  username: helloflorin
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/logo.jpg
google_analytics: UA-111647435-1
plugins:
- jekyll-feed
- jekyll-seo-tag
