theme: jekyll-theme-minimal
title: Florin Lipan
description: My personal website
url: https://lipanski.com
logo: /assets/images/logo.jpg
permalink: posts/:slug
twitter:
  username: helloflorin
  card: summary
google_analytics: UA-111647435-1
plugins:
- jekyll-feed
- jekyll-seo-tag
